export const CREATEUSER_REQUEST = "CREATEUSER_REQUEST";
export const CREATEUSER_SUCCESS = "CREATEUSER_SUCCESS";
export const CREATEUSER_ERROR = "CREATEUSER_ERROR";

export const GETUSER_REQUEST = "GETUSER_REQUEST";
export const GETUSER_SUCCESS = "GETUSER_SUCCESS";
export const GETUSER_ERROR = "GETUSER_ERROR";

export const GETIDUSER_REQUEST = "GETIDUSER_REQUEST";
export const GETIDUSER_SUCCESS = "GETIDUSER_SUCCESS";
export const GETIDUSER_ERROR = "GETIDUSER_ERROR";

export const UPDATEUSER_REQUEST = "UPDATEUSER_REQUEST";
export const UPDATEUSER_SUCCESS = "UPDATEUSER_SUCCESS";
export const UPDATEUSER_ERROR = "UPDATEUSER_ERROR";

export const DELETEUSER_REQUEST = "DELETEUSER_REQUEST";
export const DELETEUSER_SUCCESS = "DELETEUSER_SUCCESS";
export const DELETEUSER_ERROR = "DELETEUSER_ERROR";