export const Action = {
    FETCH_DATA_SUCCESS: "FETCH_DATA_SUCCESS",
    FETCH_DATA_FAILURE: "FETCH_DATA_FAILURE",
    SET_FILTERS: "SET_FILTERS",
    SET_DELETE_PRODUCTS_DIALOG: "SET_DELETE_PRODUCTS_DIALOG",
    SET_SELECTED_ROWS: "SET_SELECTED_ROWS",
    SET_DELETE_PRODUCT_DIALOG: "SET_DELETE_PRODUCT_DIALOG",
    SET_ROW_DELETED: "SET_ROW_DELETED",
  
    CREATE_USER: "CREATE_USER",
    SET_ID: "SET_ID",
    SET_DATA: "SET_DATA",
    UPDATE_USER: "UPDATE_USER",
    DELETE_USER: "DELETE_USER",
    UPDATE_FIELD: "UPDATE_FIELD",
    SET_IS_LOADING: "SET_IS_LOADING",
    SET_IS_SUBMITTING: "SET_IS_SUBMITTING",
    SET_ERROR: "SET_ERROR",
}