export const CREATE_REQUEST="CREATE_REQUEST";
export const CREATE_SUCCESS="CREATE_SUCCESS";
export const CREATE_ERROR="CREATE_ERROR"

export const GET_REQUEST="GET_REQUEST";
export const GET_SUCCESS="GET_SUCCESS";
export const GET_ERROR="GET_ERROR"

export const GETID_REQUEST="GETID_REQUEST";
export const GETID_SUCCESS="GETID_SUCCESS";
export const GETID_ERROR="GETID_ERROR"


export const UPDATE_REQUEST="UPDATE_REQUEST";
export const UPDATE_SUCCESS="UPDATE_SUCCESS";
export const UPDATE_ERROR="UPDATE_ERROR"

export const DELETE_REQUEST="DELETE_REQUEST";
export const DELETE_SUCCESS="DELETE_SUCCESS";
export const DELETE_ERROR="DELETE_ERROR"